version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  fallstudien-generator:
    image: fallstudien-generator
    container_name: fallstudien-generator
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - postgres-network
      - network
networks:
  postgres-network:
    driver: bridge
  network:
    driver: bridge
