spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration, org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  web:
    resources.static-locations: classpath:/static/
  webflux:
    static-path-pattern: /ui/**
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:postgres}:5432/${DB_SCHEMA:dev}
    username: ${DB_USER:dev}
    password: ${DB_USER:password}
  mail:
    host: ${SMTP_HOST:localhost}
    username: ${SMTP_USER:user}
    password: ${SMTP_PASS:pass}
    port: ${SMTP_PORT:587}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

generator.mail.from: ${FROM_MAIL:test@localhost}
generator.mail.cc: ${MAIL_CC:test@localhost}
