spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
  web:
    resources.static-locations: classpath:/static/
  webflux:
    static-path-pattern: /ui/*
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:postgres}:5432/dev
    username: dev
    password: password
    initialization-mode: always
